.github/workflows/release.yml

chore: change github action to fetch with all tags

---

.github/workflows/release.yml

chore: fix git fetch all tags command in github action

---

package.json
packages/babel-config-react/index.js
packages/eslint-config/index.json

affects: @medly/babel-config-react, @medly/eslint-config

fix: lint issue

---

package.json
yarn.lock

chore: add cross-env as dev dependency

---

.github/workflows/release.yml
packages/babel-config-react/package.json
packages/babel-config/package.json
packages/eslint-config-react/package.json
packages/eslint-config/package.json
packages/prettier-config/package.json
packages/rollup-config/package.json
packages/semantic-release-config/package.json
packages/typescript-config/package.json

affects: @medly/babel-config-react, @medly/babel-config, @medly/eslint-config-react,
@medly/eslint-config, @medly/prettier-config, @medly/rollup-config, @medly/semantic-release-config,
@medly/typescript-config

chore: add medly scope in release github action

---

packages/eslint-config-react/README.md
packages/eslint-config-react/package.json
packages/eslint-config/package.json
packages/rollup-config/README.md
packages/semantic-release-config/README.md
packages/typescript-config/README.md

affects: @medly/eslint-config-react, @medly/eslint-config, @medly/rollup-config,
@medly/semantic-release-config, @medly/typescript-config

docs: update readme files

---

package.json

fix: update version of medly packages

---

packages/rollup-config/index.js
packages/semantic-release-config/package.json

affects: @medly/rollup-config, @medly/semantic-release-config

docs: update minor content to publish latest readme

---

packages/babel-config-react/package.json
packages/babel-config/index.js

affects: @medly/babel-config-react, @medly/babel-config
Add `@medly/babel-config` as dependency in `@medly/babel-config-react`

fix: dependency issue in babel-config-react

---

packages/eslint-config-react/index.json
packages/eslint-config/index.json
packages/typescript-config/package.json
packages/typescript-config/tsconfig.json
yarn.lock

affects: @medly/eslint-config-react, @medly/eslint-config, @medly/typescript-config

refactor: eslint & typescript config to support jest

---

package.json
yarn.lock

fix: lint issue by adding jest as dev dependency

---

.github/workflows/release.yml
.vscode/settings.json
lerna.json
package.json
tsconfig.json
types/jest-dom.d.ts
types/module.d.ts

refactor: remove unwanted files

---

packages/stylelint-config/README.md
packages/stylelint-config/index.json
packages/stylelint-config/package.json
yarn.lock

affects: @medly/stylelint-config

feat: add package for stylelint config

---

packages/stylelint-config/package.json
yarn.lock

affects: @medly/stylelint-config

fix: stylelint & prettier issue by adding stylelint-config-prettier

---

yarn.lock

fix: yarn lock issue while bumping the package version

---

packages/webpack-config/README.md
packages/webpack-config/index.js
packages/webpack-config/package.json
packages/webpack-config/webpack.common.js
packages/webpack-config/webpack.dev.js
packages/webpack-config/webpack.prod.js
yarn.lock

feat: add package for webpack config

---

packages/webpack-config/package.json
yarn.lock

fix: add webpack-dev-server to fix webpack serve issue

---

yarn.lock

fix: ci issue

---

packages/webpack-config/README.md
packages/webpack-config/index.js

refactor: use mode instead of env for running webpack

---

package.json
packages/babel-config-react/package.json
packages/babel-config/package.json
packages/eslint-config-react/package.json
packages/eslint-config/package.json
packages/prettier-config/package.json
packages/rollup-config/package.json
packages/semantic-release-config/package.json
packages/stylelint-config/package.json
packages/typescript-config-react/package.json
packages/typescript-config/package.json
packages/webpack-config/package.json
yarn.lock

affects: @medly/babel-config-react, @medly/babel-config, @medly/eslint-config-react,
@medly/eslint-config, @medly/prettier-config, @medly/rollup-config, @medly/semantic-release-config,
@medly/stylelint-config, @medly/typescript-config-react, @medly/typescript-config,
@medly/webpack-config

fix: dependency warning

---

yarn.lock

fix: update yarn lock

---

packages/webpack-config/configs/webpack.dev.js

fix: remove deprecated option from webpack-dev-server

---

README.md

SW | docs: adds agenda for using Medly config in readme

---

packages/eslint-config-react/index.json

affects: @medly/eslint-config-react

fix: suppress explicit-module-boundary-types rule

---

packages/webpack-config/README.md
packages/webpack-config/configs/webpack.common.js

fix: copy whole public folder instead of static folder in it

---

README.md
packages/babel-config-react/README.md
packages/babel-config/README.md
packages/eslint-config-react/README.md
packages/eslint-config/README.md
packages/jest-config-react/README.md
packages/prettier-config/README.md
packages/rollup-config/README.md
packages/semantic-release-config/README.md
packages/stylelint-config/README.md
packages/typescript-config-react/README.md
packages/typescript-config/README.md
packages/webpack-config/README.md

affects: @medly/babel-config-react, @medly/babel-config, @medly/eslint-config-react,
@medly/eslint-config, @medly/jest-config-react, @medly/prettier-config, @medly/rollup-config,
@medly/semantic-release-config, @medly/stylelint-config, @medly/typescript-config-react,
@medly/typescript-config, @medly/webpack-config

docs: update readme with language/tools logo

---

README.md
packages/babel-config-react/README.md
packages/babel-config/README.md
packages/eslint-config-react/README.md
packages/eslint-config/README.md
packages/jest-config-react/README.md
packages/prettier-config/README.md
packages/rollup-config/README.md
packages/semantic-release-config/README.md
packages/stylelint-config/README.md
packages/typescript-config-react/README.md
packages/typescript-config/README.md
packages/webpack-config/README.md

affects: @medly/babel-config-react, @medly/babel-config, @medly/eslint-config-react,
@medly/eslint-config, @medly/jest-config-react, @medly/prettier-config, @medly/rollup-config,
@medly/semantic-release-config, @medly/stylelint-config, @medly/typescript-config-react,
@medly/typescript-config, @medly/webpack-config

docs: fix logo height issue

---

packages/jest-config-react/setupAfterEnv.js

affects: @medly/jest-config-react

feat: add default mock for window.matchMedia

---

.github/workflows/release.yml

feat: add admin token to push commits on protected branch

---

packages/semantic-release-config/index.json

affects: @medly/semantic-release-config

refactor: change default branch name from master to main

---

.gitignore
.husky/commit-msg
.husky/prepare-commit-msg
package.json
yarn.lock

feat: upgrade husky version to 6

---

packages/babel-config-react/package.json
packages/jest-config-react/package.json
packages/webpack-config/package.json

affects: @medly/babel-config-react, @medly/jest-config-react, @medly/webpack-config

fix: react, react-dom, styled-components peer dependency version warning

---

package.json

pre-commit hook is running in release workflow
skipping all hooks in release workflow

fix: skip husky in release workflow

---

packages/semantic-release-config/index.json

affects: @medly/semantic-release-config
The current commit message also includes `[skip ci]`
Remove `[skip ci]` from commit message.

refactor: semantic release commit message

---

packages/babel-config-react/index.js
packages/eslint-config/index.json
packages/rollup-config/index.js
packages/rollup-config/package.json
yarn.lock

affects: @medly/babel-config-react, @medly/eslint-config, @medly/rollup-config

feat: add svg support

---

packages/babel-config-react/index.js

affects: @medly/babel-config-react

fix: svg loader issue

---

packages/rollup-config/index.js

feat: use runtime as babelHelpers in rollup

---

packages/webpack-config/configs/webpack.common.js
packages/webpack-config/package.json
yarn.lock

feat: add file loader to support png, jpeg, gif in webpack config

---

packages/webpack-config/index.d.ts
packages/webpack-config/package.json

feat: add types for webpack config's configure function

---

packages/rollup-config/index.d.ts
packages/rollup-config/package.json

affects: @medly/rollup-config
There are no types for configure function.
Added types for configure function.

feat: add types for rollup config's configure function

---

packages/jest-config-react/index.d.ts
packages/jest-config-react/package.json
packages/rollup-config/package.json

affects: @medly/jest-config-react, @medly/rollup-config

feat(jest-config-react): add types for configure method exported by '@medly/jest-config-react'

---

.github/workflows/release.yml

fix: remove token for checking out the repo in release workflow

---

.github/workflows/release.yml

fix: add github token in checkout repo step in release workflow

---

.github/workflows/release.yml
lerna.json
packages/semantic-release-config/index.json

affects: @medly/semantic-release-config

refactor: trigger release workflow on push instead of pull_request merge

---

packages/jest-config-react/setupAfterEnv.js

affects: @medly/jest-config-react

fix: error thrown from jest-axe

---

packages/rollup-config/index.js

affects: @medly/rollup-config
Building packages using rollup is failing.
Added `skipPreflightCheck: true` to rollup config to fix the issue.

fix: babel runtime issue in rollup config

---

packages/babel-config/index.js
packages/eslint-config/package.json
packages/rollup-config/index.js
packages/rollup-config/package.json
packages/typescript-config-react/package.json
packages/typescript-config/package.json
yarn.lock

affects: @medly/babel-config, @medly/eslint-config, @medly/rollup-config,
@medly/typescript-config-react, @medly/typescript-config

fix: rollup build hang issue

---

yarn.lock

fix: yarn update

---

packages/eslint-config-react/package.json
packages/eslint-config/package.json

This resolves linting issues caused by environment globals.
Current behavior does not support global browser variables like `window`
The new behavior allows global variables access

add(es-lint-config): Add env support

---

packages/eslint-config-react/index.json

affects: @medly/eslint-config-react
Added `react/jsx-fragments` & `react/self-closing-comp` rule.

feat: add rules for fragments and closing comp in eslint

---

packages/eslint-config-react/index.json
packages/jest-config-react/index.js
packages/rollup-config/index.js
packages/typescript-config-react/tsconfig.json
packages/typescript-config/tsconfig.json
packages/webpack-config/configs/webpack.common.js
packages/webpack-config/package.json
yarn.lock

affects: @medly/eslint-config-react, @medly/jest-config-react, @medly/rollup-config,
@medly/typescript-config-react, @medly/typescript-config, @medly/webpack-config

refactor: multiple packages

---

yarn.lock

fix: fix yarn lock issue

---

yarn.lock

fix: fix yarn lock changes

---

packages/typescript-config-react/package.json
packages/typescript-config/package.json
packages/typescript-config/tsconfig.json

affects: @medly/typescript-config-react, @medly/typescript-config

feat: add strict null check in typescript config

---

packages/babel-config-react/index.js
packages/babel-config-react/package.json
packages/typescript-config-react/tsconfig.json
yarn.lock

affects: @medly/babel-config-react, @medly/typescript-config-react
Using the latest JSX transform -> [Source](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)

feat: use new jsx transform in react app

---

packages/eslint-config-react/index.json
packages/eslint-config/index.json

affects: @medly/eslint-config-react, @medly/eslint-config
Applying testing-library rules only on test files.

refactor: add testing library rules only on test files

---

packages/webpack-config/configs/webpack.common.js
packages/webpack-config/package.json
yarn.lock

feat: add url-loader for importing font files in weboack config

---

packages/babel-config-react/index.js

affects: @medly/babel-config-react
Not able to create production build with `data-testid`
We can create production build `data-testid` also.

feat: add data testid check in babel config

---

packages/webpack-config/package.json

(Replace This Text: Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.)
(Replace This Text: Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.)
[ ] Test A
[ ] Test B
(Replace This Text: Please enter the issue number.)
(Replace This Text: Please describe the current behaviour you are modifying, or link a relevant issue.)
(Replace This Text: Please describe the expected new behaviour.)
**Note:** (Replace This Text: If this PR contains a breaking change please describe the impact and migration path for existing …

feat: ISSUE-95 | upgrade webpack-config dep 

---

packages/eslint-config-react/index.json
packages/eslint-config-react/package.json
yarn.lock

affects: @medly/eslint-config-react
(Replace This Text: Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.)

feat: add html eslint plugin
